/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#050816',
        surface: '#0f1321',
        'surface-dim': '#0f1321',
        'surface-bright': '#353849',
        'surface-container-lowest': '#0a0d1c',
        'surface-container-low': '#171b2a',
        'surface-container': '#1b1f2e',
        'surface-container-high': '#262939',
        'surface-container-highest': '#303444',
        'on-surface': '#dfe1f6',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#dfe1f6',
        'inverse-on-surface': '#2c303f',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'surface-tint': '#00dbe7',
        primary: '#e1fdff',
        'on-primary': '#00363a',
        'primary-container': '#00f2ff',
        'on-primary-container': '#006a71',
        'inverse-primary': '#00696f',
        secondary: '#c0c1ff',
        'on-secondary': '#1000a9',
        'secondary-container': '#3131c0',
        'on-secondary-container': '#b0b2ff',
        tertiary: '#fef4ff',
        'on-tertiary': '#490080',
        'tertiary-container': '#ebd1ff',
        'on-tertiary-container': '#852cd3',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#74f5ff',
        'primary-fixed-dim': '#00dbe7',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'tertiary-fixed': '#f0dbff',
        'tertiary-fixed-dim': '#ddb7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'panel-gap': '16px',
        'container-padding': '40px',
        gutter: '24px',
        'glass-padding': '24px',
      },
      fontFamily: {
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'data-metric': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Geist', 'Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
